apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.nodeName }}
    chain: bsc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nodeName }}
  ports:
  - name: http
    port: {{ .Values.service.ports.http.port }}
    targetPort: http
    protocol: TCP
  - name: ws
    port: {{ .Values.service.ports.ws.port }}
    targetPort: ws
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.ports.metrics.port }}
    targetPort: metrics
    protocol: TCP
  - name: p2p
    port: {{ .Values.service.ports.p2p.port }}
    targetPort: p2p
    protocol: TCP
  - name: p2p-udp
    port: {{ .Values.service.ports.p2p.port }}
    targetPort: p2p-udp
    protocol: UDP
  {{- if and .Values.monitoring .Values.monitoring.enabled .Values.monitoring.gethExporter.enabled }}
  - name: geth-exporter
    port: {{ .Values.monitoring.gethExporter.port }}
    targetPort: exporter
    protocol: TCP
  {{- end }}
